# Generated by Django 5.0.1 on 2024-01-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='celphonea',
            new_name='celphone',
        ),
    ]
