# Generated by Django 5.0.1 on 2024-01-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_celphonea_customer_celphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='status',
            new_name='activate',
        ),
    ]
